package Zaur_OOP.podpaket_lesson27_exceptions_and_mistakes.the_final_part;

public class Test3 {
    void abc()throws Exception{
        System.out.println("ok");
    }
}
